# Generated by Django 4.2.7 on 2026-04-05 10:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Examen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("type", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[("en_attente", "En attente"), ("complet", "Complet")],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=100)),
                (
                    "prenom",
                    models.CharField(default="Adresse inconnue", max_length=100),
                ),
                (
                    "phonenumber",
                    models.CharField(default="Adresse inconnue", max_length=15),
                ),
                ("date_naissance", models.DateField(default=datetime.date(2000, 1, 1))),
                (
                    "email",
                    models.EmailField(
                        default="Adresse inconnue", max_length=254, unique=True
                    ),
                ),
                (
                    "adresse",
                    models.CharField(default="Adresse inconnue", max_length=150),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titre",
                    models.CharField(
                        choices=[
                            ("radiologue", "Radiologue"),
                            ("chef_service", "Chef de service"),
                            ("admin", "Administrateur"),
                            ("secretaire", "Secrétaire"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "group",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role",
                        to="auth.group",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("nom_hopital", models.CharField(max_length=150)),
                ("adresse", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Compte",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(default="Prénom inconnu", max_length=100)),
                (
                    "phonenumber",
                    models.CharField(default="Numéro inconnu", max_length=10),
                ),
                (
                    "date_naissance",
                    models.DateField(default=datetime.datetime(2000, 1, 1, 0, 0)),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "adresse",
                    models.CharField(default="Adresse inconnue", max_length=150),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="dernière connexion"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(default=False, verbose_name="superuser status"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                ("roles", models.ManyToManyField(blank=True, to="APPI.role")),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "compte_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Administrateur",
                "verbose_name_plural": "Administrateurs",
            },
            bases=("APPI.compte",),
        ),
        migrations.CreateModel(
            name="ChefService",
            fields=[
                (
                    "compte_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Chef de service",
                "verbose_name_plural": "Chefs de service",
            },
            bases=("APPI.compte",),
        ),
        migrations.CreateModel(
            name="Radiologue",
            fields=[
                (
                    "compte_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Radiologue",
                "verbose_name_plural": "Radiologues",
            },
            bases=("APPI.compte",),
        ),
        migrations.CreateModel(
            name="RDV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("lieu", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(default="Examen (mammographie)", max_length=100),
                ),
                ("status", models.CharField(default="Planifié", max_length=50)),
                ("accepte", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_rdvs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rdvs",
                        to="APPI.patient",
                    ),
                ),
                (
                    "radiologue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rdvs",
                        to="APPI.radiologue",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rapport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("contenu", models.TextField()),
                (
                    "date_creation",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[("en_attente", "En attente"), ("complet", "Complet")],
                        max_length=50,
                    ),
                ),
                (
                    "examen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rapports",
                        to="APPI.examen",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImageRadiologique",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("path", models.CharField(max_length=400)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "modalite",
                    models.CharField(
                        choices=[
                            ("IRM", "IRM (Imagerie par Résonance Magnétique)"),
                            ("MAMO", "MAMO (Mammographie)"),
                            ("ECO", "ECHO (Échographie)"),
                        ],
                        max_length=4,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imageRadiologique",
                        to="APPI.patient",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="examen",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="APPI.patient"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="radiologue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patients",
                to="APPI.radiologue",
            ),
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(verbose_name="Message")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "date_creation",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("read", models.BooleanField(default=False, verbose_name="Lu")),
                ("lu", models.BooleanField(default=False, verbose_name="Lu (alias)")),
                (
                    "type",
                    models.CharField(
                        default="info",
                        max_length=50,
                        verbose_name="Type de notification",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications_patient",
                        to="APPI.patient",
                        verbose_name="Patient associé",
                    ),
                ),
                (
                    "rdv",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="APPI.rdv",
                        verbose_name="Rendez-vous associé",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Destinataire",
                    ),
                ),
                (
                    "radiologue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications_radiologue",
                        to="APPI.radiologue",
                        verbose_name="Radiologue destinataire",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
            },
        ),
    ]
