# Generated by Django 4.2.7 on 2026-04-13 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("APPI", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="ai_model",
            field=models.CharField(
                choices=[
                    ("none", "Aucun"),
                    ("YOLOV11_ECO", "YOLOv11 - Echographie"),
                    ("YOLOV11_IRM", "YOLOv11 - IRM"),
                    ("YOLOV11_MAMO", "YOLOv11 - Mammographie"),
                ],
                default="none",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="modalite",
            field=models.CharField(
                choices=[
                    ("xray", "Radiographie (X-Ray)"),
                    ("irm", "IRM"),
                    ("mammographie", "Mammographie"),
                    ("echographie", "Echographie"),
                    ("scanner", "Scanner (CT)"),
                ],
                default="xray",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="organe",
            field=models.CharField(
                choices=[
                    ("thorax", "Thorax"),
                    ("abdomen", "Abdomen"),
                    ("cerveau", "Cerveau"),
                    ("sein", "Sein"),
                    ("os", "Os / Articulations"),
                    ("coeur", "Coeur"),
                    ("pelvis", "Pelvis"),
                    ("colonne", "Colonne vertébrale"),
                    ("autre", "Autre"),
                ],
                default="autre",
                max_length=50,
            ),
        ),
    ]
