# Generated by Django 4.2.7 on 2026-04-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("APPI", "0002_service_ai_model_service_modalite_service_organe"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="ai_model",
        ),
        migrations.RemoveField(
            model_name="service",
            name="modalite",
        ),
        migrations.RemoveField(
            model_name="service",
            name="organe",
        ),
        migrations.AddField(
            model_name="service",
            name="ai_models",
            field=models.CharField(blank=True, default="none", max_length=255),
        ),
        migrations.AddField(
            model_name="service",
            name="modalites",
            field=models.CharField(blank=True, default="xray", max_length=255),
        ),
        migrations.AddField(
            model_name="service",
            name="organes",
            field=models.CharField(blank=True, default="autre", max_length=255),
        ),
    ]
